#dev version of configuration  and Multipart file setting
server:
  port: 8081
  servlet:
    context-path: /api/v1
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 1KB


#database configuration

spring:
  datasource:
    url: ${DB_URL}
#    url: jdbc:postgresql://127.0.0.1:5432/vidyara
#    username: postgres
#    password: Postgresql@Om123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: {org.hibernate.dialect.PostgreSQLDialect}
    show-sql: true


#jwt security configuration
security:
  jwt:
    secret: ${JWT_SECRET:dfufosdfpsioiu7d892rif89as&ioU8UFMOIVUIO_UYadi_D89F_89DFYUIDFYSUIAYDFUISDFOSDFHKSKDFJKJQEYIJUOasoUW89R}
    issuer: ${JWT_ISSUER:api.vidyara.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}

  cookie:
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    secure: false
    http-only: true
    same-site: lax

#logging config
logging:
  level:
    org.springframework.security: DEBUG

#cors config
app:
    front-end-url: http://localhost:5173
    domain: ${DOMAIN:localhost}
    file-store-url: ${FILE_STORE_URL:src/main/resources/files}

cloudflare:
  r2:
    account-id: ${R2_ACCOUNT_ID}
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    bucket-name: ${R2_BUCKET_NAME}